/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import org.apache.commons.io.FileUtils;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import static out.transparent.error.ErrorOutJOptions.error01Transparent32px;

/**
 *
 * @author Wesley
 */
public class Ui extends javax.swing.JFrame {

    public static String conteudo;
    public static Converter t;
    public static Converter p;
    public static Converter h;
    public static Converter d;

    /**
     * Creates new form Ui
     */
    public Ui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        generate = new javax.swing.JButton();
        open = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        barraProgresso = new javax.swing.JProgressBar();
        status = new javax.swing.JLabel();
        separador0 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        separador1 = new javax.swing.JTextField();
        separador2 = new javax.swing.JTextField();
        radioButton01 = new javax.swing.JRadioButton();
        radioButton02 = new javax.swing.JRadioButton();
        radioButton03 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        generate.setText("Gerar Gráfico");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        open.setText("Abrir arquivo");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        barraProgresso.setFocusable(false);

        jLabel1.setText("Separar por:");

        radioButton01.setText("Temperatura / Data / Pressão");
        radioButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton01ActionPerformed(evt);
            }
        });

        radioButton02.setText("Temperatura / Data");
        radioButton02.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioButton02StateChanged(evt);
            }
        });
        radioButton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton02ActionPerformed(evt);
            }
        });

        radioButton03.setText("Pressão / Data");
        radioButton03.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioButton03StateChanged(evt);
            }
        });
        radioButton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton03ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(generate)
                        .addGap(18, 18, 18)
                        .addComponent(open)
                        .addGap(16, 16, 16)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButton03)
                            .addComponent(jLabel1)
                            .addComponent(radioButton01)
                            .addComponent(radioButton02)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barraProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(separador0, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generate)
                    .addComponent(open)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButton02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButton03)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(separador0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        if (radioButton02.isSelected()) {
            t = new Converter(conteudo, "temperatura", false);
            h = new Converter(conteudo, "hora", "data", true, true);

        } else if (radioButton01.isSelected()) {
            t = new Converter(conteudo, "temperatura", false);
            h = new Converter(conteudo, "hora", "data", true, true);
            p = new Converter(conteudo, "pressao", false);
        } else if (radioButton03.isSelected()) {
            h = new Converter(conteudo, "hora", "data", true, true);
            p = new Converter(conteudo, "pressao", false);
        }

        JFreeChart chart = Generate.createChart(Generate.createDataset());

        ChartFrame chartFrm = new ChartFrame("Dados", chart, true);

        chartFrm.setVisible(true);
        chartFrm.setSize(1000, 700);
    }//GEN-LAST:event_generateActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                textArea.read(new FileReader(file.getAbsolutePath()), null);
                conteudo = FileUtils.readFileToString(file, "UTF-8");

                //int janelaProcessamento = 4;
                //ScheduledExecutorService executor = Executors.newScheduledThreadPool(janelaProcessamento);
                // executor.execute(new FileProcessor());
            } catch (NumberFormatException e) {
                error01Transparent32px("Arquivo inválido carregado" + "\n" + file.getAbsolutePath(), "Erro");
                // JOptionPane.showMessageDialog(null, "Arquivo inválido carregado" + "\n" +file.getAbsolutePath(), "Erro", JOptionPane.ERROR_MESSAGE, erroIcone);
                // mostrarValoresOrdenados.setText("Arquivo inválido carregado");
                textArea.setText("Arquivo inválido carregado");
            } catch (IOException ex) {
                // Logger.getLogger(OrdenacaoUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            // JOptionPane.showMessageDialog(null, "Nenhum arquivo carregado" + file.getAbsolutePath(), "Erro", JOptionPane.ERROR_MESSAGE, erroIcone);

        } else {
            error01Transparent32px("Nenhum arquivo carregado", "Erro");
            //  JOptionPane.showMessageDialog(null, "Nenhum arquivo carregado", "Erro", JOptionPane.ERROR_MESSAGE, erroIcone);

        }
    }//GEN-LAST:event_openActionPerformed

    private void radioButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton01ActionPerformed
        radioButton02.setSelected(false);
        radioButton03.setSelected(false);

        separador0.setText("temperatura");
        separador1.setText("hora");
        separador2.setText("pressao");
    }//GEN-LAST:event_radioButton01ActionPerformed

    private void radioButton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton02ActionPerformed
        radioButton01.setSelected(false);
        radioButton03.setSelected(false);
        separador0.setText("temperatura");
        separador1.setText("hora");
        separador2.setText("");
    }//GEN-LAST:event_radioButton02ActionPerformed

    private void radioButton02StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioButton02StateChanged

    }//GEN-LAST:event_radioButton02StateChanged

    private void radioButton03StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioButton03StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButton03StateChanged

    private void radioButton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton03ActionPerformed
        radioButton01.setSelected(false);
        radioButton02.setSelected(false);
        separador0.setText("pressão");
        separador1.setText("hora");
        separador2.setText("");
    }//GEN-LAST:event_radioButton03ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar barraProgresso;
    public static javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton generate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JButton open;
    public static javax.swing.JRadioButton radioButton01;
    public static javax.swing.JRadioButton radioButton02;
    public static javax.swing.JRadioButton radioButton03;
    public static javax.swing.JTextField separador0;
    public static javax.swing.JTextField separador1;
    public static javax.swing.JTextField separador2;
    public static javax.swing.JLabel status;
    public static javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
